nifty_100_tickers = [
    "ABB", "ADANIENSOL", "ADANIENT", "ADANIGREEN", "ADANIPORTS", "ADANIPOWER", 
    "AMBUJACEM", "APOLLOHOSP", "ASIANPAINT", "AVEU", "AXISBANK", "BAJAJ-AUTO", 
    "BAJFINANCE", "BAJAJFINSV", "BAJAJHLDNG", "BANKBARODA", "BEL", "BPCL", 
    "BHARTIARTL", "BHEL", "BOSH", "BRITANNIA", "CANBK", "CHOLAFIN", "CIPLA", 
    "COALINDIA", "DABUR", "DIVISLAB", "DLF", "DRREDDY", "EICHERMOT", "GAIL", 
    "GODREJCP", "GRASIM", "HAVELLS", "HCLTECH", "HDFCBANK", "HDFCLIFE", "HEROMOTOCO", 
    "HINDALCO", "HAL", "HINDUNILVR", "HINDZINC", "ICICIBANK", "ICICIGI", "ICICIPRULI", 
    "IDFCFIRSTB", "INDHOTEL", "INDIGO", "INDUSINDBK", "INFY", "IOC", "IRCTC", 
    "IRFC", "ITC", "JINDALSTEL", "JIOFIN", "JSWSTEEL", "JSWENERGY", "KOTAKBANK", 
    "LTIM", "LT", "LICI", "M&M", "MARICO", "MARUTI", "MOTHERSON", "MPHASIS", 
    "NESTLEIND", "NTPC", "NHPC", "ONGC", "PAGEIND", "PIDILITIND", "PFC", 
    "POWERGRID", "PNB", "RELIANCE", "REC", "SBICARD", "SBILIFE", "SBIN", 
    "SHREECEM", "SHRIRAMFIN", "SIEMENS", "SRF", "SUNPHARMA", "TATACONSUM", 
    "TATAMOTORS", "TATAPOWER", "TATASTEEL", "TCS", "TECHM", "TITAN", 
    "TORNTPHARM", "TRENT", "TVSMOTOR", "ULTRACEMCO", "UNITDSPR", "VBL", 
    "VEDL", "WIPRO", "ZOMATO", "ZYDUSLIFE"
]


nifty_50_tickers = [
    "ADANIENT", "ADANIPORTS", "APOLLOHOSP", "ASIANPAINT", "AXISBANK", 
    "BAJAJ-AUTO", "BAJFINANCE", "BAJAJFINSV", "BEL", "BPCL", 
    "BHARTIARTL", "BRITANNIA", "CIPLA", "COALINDIA", "DIVISLAB", 
    "DRREDDY", "EICHERMOT", "GRASIM", "HCLTECH", "HDFCBANK", 
    "HDFCLIFE", "HEROMOTOCO", "HINDALCO", "HINDUNILVR", "ICICIBANK", 
    "INDUSINDBK", "INFY", "ITC", "JSWSTEEL", "KOTAKBANK", 
    "LTIM", "LT", "M&M", "MARUTI", "NESTLEIND", 
    "NTPC", "ONGC", "POWERGRID", "RELIANCE", "SBILIFE", 
    "SBIN", "SHRIRAMFIN", "SUNPHARMA", "TATACONSUM", "TATAMOTORS", 
    "TATASTEEL", "TCS", "TECHM", "TITAN", "ULTRACEMCO"
]
